# h4_api_environment: staging
# h4_api_name: h4_api

# server_name: localhost
# root_dir: "/var/www/silentlog.com/current/public"
# uwsgi_params_path: "/etc/nginx/uwsgi_params"

# mackerel_apikey: "@mackerel_key"

# usergroup:
#   user:
#     name: nginx
#     group: nginx

# app_path: "/var/www/silentlog.com"

# hash_code: "a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1"

# elastic_search_endpoint: ""